"""first test

Revision ID: 23bc4aa0a0f4
Revises: 
Create Date: 2020-02-04 20:24:11.395565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bc4aa0a0f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_username', table_name='admin')
    op.drop_table('admin')
    op.drop_index('ix_chatbot_name', table_name='chatbot')
    op.drop_table('chatbot')
    op.drop_table('botobject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botobject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chatbot_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatbot_id')
    )
    op.create_table('chatbot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lang', sa.INTEGER(), nullable=True),
    sa.Column('bot_type', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_name', 'chatbot', ['name'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_username', 'admin', ['username'], unique=1)
    # ### end Alembic commands ###
